"""ABI definitions loaded from JSON files generated by `scripts/tempo_abis.sh --sync`."""

import json
from pathlib import Path

_DIR = Path(__file__).parent


def _load(name: str) -> list:
    with open(_DIR / f"{name}.json") as f:
        return json.load(f)


TIP20_ABI = _load("ITIP20")
TIP20_ROLES_AUTH_ABI = _load("ITIP20RolesAuth")
ACCOUNT_KEYCHAIN_ABI = _load("IAccountKeychain")
STABLECOIN_DEX_ABI = _load("IStablecoinDEX")
FEE_MANAGER_ABI = _load("IFeeManager")
FEE_AMM_ABI = _load("IFeeAMM")
NONCE_ABI = _load("INonce")
TIP403_REGISTRY_ABI = _load("ITIP403Registry")
RECEIVE_POLICY_GUARD_ABI = _load("IReceivePolicyGuard")
SIGNATURE_VERIFIER_ABI = _load("ISignatureVerifier")
CURRENT_COMMITTEE_ABI = _load("ICurrentCommittee")
