name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: wevm/changelogs@04ccca87f4785039ced6da0fff27ba29c0dd9f5c # master
        with:
          ecosystem: python
          python-version: '3.12'
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          conventional-commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
